import { mutation } from "./_generated/server";

export const seedTestData = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if we already have enough data
    const existingAlumni = await ctx.db.query("alumni").collect();
    if (existingAlumni.length >= 15) {
      return { success: true, message: `Database already has ${existingAlumni.length} alumni profiles.` };
    }

    // Create test users - expanded list
    const users = [
      { name: "Sarah Johnson", email: "sarah@example.com" },
      { name: "Michael Chen", email: "michael@example.com" },
      { name: "Emily Rodriguez", email: "emily@example.com" },
      { name: "David Kim", email: "david@example.com" },
      { name: "Priya Sharma", email: "priya@example.com" },
      { name: "James Wilson", email: "james@example.com" },
      { name: "Maria Garcia", email: "maria@example.com" },
      { name: "Robert Taylor", email: "robert@example.com" },
      { name: "Aisha Patel", email: "aisha@example.com" },
      { name: "Daniel Brown", email: "daniel@example.com" },
      { name: "Lisa Anderson", email: "lisa@example.com" },
      { name: "Kevin Zhang", email: "kevin@example.com" },
      { name: "Sophia Martinez", email: "sophia@example.com" },
      { name: "Thomas Lee", email: "thomas@example.com" },
      { name: "Nina Kowalski", email: "nina@example.com" },
    ];

    const userIds = await Promise.all(
      users.map((u) =>
        ctx.db.insert("users", {
          name: u.name,
          email: u.email,
          image: undefined,
          emailVerificationTime: undefined,
          isAnonymous: false,
          role: "member",
        }),
      ),
    );

    // Create test alumni profiles (linked to created users) - expanded list
    const testAlumni = [
      {
        firstName: "Sarah",
        lastName: "Johnson",
        graduationYear: 2018,
        degree: "Bachelor of Science",
        major: "Computer Science",
        currentPosition: "Senior Software Engineer",
        currentCompany: "Tech Corp",
        location: "San Francisco, CA",
        bio: "Passionate about building scalable web applications and mentoring junior developers.",
        linkedinUrl: "https://linkedin.com/in/sarahjohnson",
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["JavaScript", "React", "Node.js", "Python"],
        interests: ["Web Development", "AI/ML", "Startups"],
      },
      {
        firstName: "Michael",
        lastName: "Chen",
        graduationYear: 2015,
        degree: "Master of Business Administration",
        major: "Business Administration",
        currentPosition: "Product Manager",
        currentCompany: "Innovation Labs",
        location: "New York, NY",
        bio: "Product leader with 8+ years experience in fintech and healthcare.",
        linkedinUrl: "https://linkedin.com/in/michaelchen",
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["Product Management", "Strategy", "Analytics"],
        interests: ["Fintech", "Healthcare", "Product Strategy"],
      },
      {
        firstName: "Emily",
        lastName: "Rodriguez",
        graduationYear: 2020,
        degree: "Bachelor of Arts",
        major: "Marketing",
        currentPosition: "Marketing Director",
        currentCompany: "Creative Agency",
        location: "Austin, TX",
        bio: "Creative marketing professional specializing in digital campaigns and brand strategy.",
        linkedinUrl: undefined,
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: false,
        skills: ["Digital Marketing", "Brand Strategy", "Content Creation"],
        interests: ["Digital Marketing", "Creative Design", "Social Media"],
      },
      {
        firstName: "David",
        lastName: "Kim",
        graduationYear: 2012,
        degree: "Bachelor of Engineering",
        major: "Mechanical Engineering",
        currentPosition: "Engineering Manager",
        currentCompany: "Manufacturing Inc",
        location: "Detroit, MI",
        bio: "Engineering leader focused on sustainable manufacturing and process optimization.",
        linkedinUrl: undefined,
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["Mechanical Engineering", "Project Management", "Sustainability"],
        interests: ["Sustainable Technology", "Manufacturing", "Leadership"],
      },
      {
        firstName: "Priya",
        lastName: "Sharma",
        graduationYear: 2019,
        degree: "Master of Science",
        major: "Data Science",
        currentPosition: "Data Scientist",
        currentCompany: "Analytics Pro",
        location: "Seattle, WA",
        bio: "Data scientist specializing in machine learning and predictive analytics.",
        linkedinUrl: "https://linkedin.com/in/priyasharma",
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["Python", "Machine Learning", "SQL", "Data Visualization"],
        interests: ["AI/ML", "Big Data", "Statistics"],
      },
      {
        firstName: "James",
        lastName: "Wilson",
        graduationYear: 2016,
        degree: "Bachelor of Arts",
        major: "Graphic Design",
        currentPosition: "Creative Director",
        currentCompany: "Design Studio",
        location: "Los Angeles, CA",
        bio: "Award-winning designer with expertise in branding and user experience.",
        linkedinUrl: undefined,
        twitterUrl: "https://twitter.com/jameswilson",
        websiteUrl: "https://jameswilson.design",
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["UI/UX Design", "Branding", "Adobe Creative Suite", "Figma"],
        interests: ["Design", "Art", "Photography"],
      },
      {
        firstName: "Maria",
        lastName: "Garcia",
        graduationYear: 2017,
        degree: "Bachelor of Science",
        major: "Biology",
        currentPosition: "Research Scientist",
        currentCompany: "BioTech Labs",
        location: "Boston, MA",
        bio: "Biomedical researcher focused on cancer therapeutics and drug development.",
        linkedinUrl: "https://linkedin.com/in/mariagarcia",
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["Molecular Biology", "Research", "Lab Management"],
        interests: ["Biotechnology", "Healthcare", "Research"],
      },
      {
        firstName: "Robert",
        lastName: "Taylor",
        graduationYear: 2014,
        degree: "Bachelor of Science",
        major: "Finance",
        currentPosition: "Investment Banker",
        currentCompany: "Global Finance Corp",
        location: "Chicago, IL",
        bio: "Finance professional with expertise in mergers and acquisitions.",
        linkedinUrl: "https://linkedin.com/in/roberttaylor",
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: false,
        skills: ["Financial Analysis", "M&A", "Valuation", "Excel"],
        interests: ["Finance", "Economics", "Investment"],
      },
      {
        firstName: "Aisha",
        lastName: "Patel",
        graduationYear: 2021,
        degree: "Bachelor of Arts",
        major: "Psychology",
        currentPosition: "UX Researcher",
        currentCompany: "User Insights Inc",
        location: "Portland, OR",
        bio: "UX researcher passionate about understanding user behavior and improving digital experiences.",
        linkedinUrl: undefined,
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: false,
        skills: ["User Research", "Usability Testing", "Data Analysis"],
        interests: ["UX Design", "Psychology", "Human Behavior"],
      },
      {
        firstName: "Daniel",
        lastName: "Brown",
        graduationYear: 2013,
        degree: "Master of Science",
        major: "Electrical Engineering",
        currentPosition: "Hardware Engineer",
        currentCompany: "Electronics Corp",
        location: "San Jose, CA",
        bio: "Hardware engineer specializing in embedded systems and IoT devices.",
        linkedinUrl: "https://linkedin.com/in/danielbrown",
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["Embedded Systems", "Circuit Design", "IoT", "C/C++"],
        interests: ["Hardware", "IoT", "Robotics"],
      },
      {
        firstName: "Lisa",
        lastName: "Anderson",
        graduationYear: 2019,
        degree: "Bachelor of Science",
        major: "Environmental Science",
        currentPosition: "Sustainability Consultant",
        currentCompany: "Green Solutions",
        location: "Denver, CO",
        bio: "Environmental consultant helping companies achieve sustainability goals.",
        linkedinUrl: undefined,
        twitterUrl: undefined,
        websiteUrl: "https://greensolutions.com/lisa",
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["Sustainability", "Environmental Policy", "Project Management"],
        interests: ["Climate Change", "Renewable Energy", "Conservation"],
      },
      {
        firstName: "Kevin",
        lastName: "Zhang",
        graduationYear: 2016,
        degree: "Bachelor of Science",
        major: "Computer Science",
        currentPosition: "DevOps Engineer",
        currentCompany: "Cloud Systems",
        location: "Austin, TX",
        bio: "DevOps engineer focused on cloud infrastructure and automation.",
        linkedinUrl: "https://linkedin.com/in/kevinzhang",
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["AWS", "Docker", "Kubernetes", "CI/CD", "Terraform"],
        interests: ["Cloud Computing", "Automation", "Infrastructure"],
      },
      {
        firstName: "Sophia",
        lastName: "Martinez",
        graduationYear: 2018,
        degree: "Bachelor of Arts",
        major: "Journalism",
        currentPosition: "Content Strategist",
        currentCompany: "Media Group",
        location: "Miami, FL",
        bio: "Content strategist with experience in digital media and storytelling.",
        linkedinUrl: undefined,
        twitterUrl: "https://twitter.com/sophiamartinez",
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: false,
        skills: ["Content Strategy", "Writing", "SEO", "Social Media"],
        interests: ["Journalism", "Digital Media", "Storytelling"],
      },
      {
        firstName: "Thomas",
        lastName: "Lee",
        graduationYear: 2015,
        degree: "Bachelor of Science",
        major: "Civil Engineering",
        currentPosition: "Project Engineer",
        currentCompany: "Construction Co",
        location: "Houston, TX",
        bio: "Civil engineer managing large-scale infrastructure projects.",
        linkedinUrl: "https://linkedin.com/in/thomaslee",
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["Civil Engineering", "Project Management", "AutoCAD"],
        interests: ["Infrastructure", "Construction", "Urban Planning"],
      },
      {
        firstName: "Nina",
        lastName: "Kowalski",
        graduationYear: 2020,
        degree: "Bachelor of Science",
        major: "Cybersecurity",
        currentPosition: "Security Analyst",
        currentCompany: "SecureTech",
        location: "Washington, DC",
        bio: "Cybersecurity professional protecting organizations from digital threats.",
        linkedinUrl: "https://linkedin.com/in/ninakowalski",
        twitterUrl: undefined,
        websiteUrl: undefined,
        phoneNumber: undefined,
        isPublic: true,
        mentorshipAvailable: true,
        skills: ["Network Security", "Penetration Testing", "Risk Assessment"],
        interests: ["Cybersecurity", "Ethical Hacking", "Privacy"],
      },
    ];

    await Promise.all(
      testAlumni.map((alum, idx) =>
        ctx.db.insert("alumni", {
          userId: userIds[idx]!,
          ...alum,
        }),
      ),
    );

    // Create test events (linked to first two users as creators)
    const now = Date.now();
    const testEvents = [
      {
        title: "Annual Alumni Networking Mixer",
        description:
          "Join us for an evening of networking, refreshments, and reconnecting with fellow alumni.",
        startDate: now + 7 * 24 * 60 * 60 * 1000,
        endDate: now + 7 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000,
        location: "Downtown Convention Center",
        isVirtual: false,
        virtualLink: undefined,
        maxAttendees: 200,
        registrationDeadline: now + 5 * 24 * 60 * 60 * 1000,
        isPublic: true,
        category: "networking",
        imageUrl: undefined,
        createdBy: userIds[0]!,
      },
      {
        title: "Career Development Workshop",
        description:
          "Learn about the latest trends in your industry and develop your professional skills.",
        startDate: now + 14 * 24 * 60 * 60 * 1000,
        endDate: now + 14 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000,
        location: undefined,
        isVirtual: true,
        virtualLink: "https://zoom.us/j/123456789",
        maxAttendees: 100,
        registrationDeadline: now + 12 * 24 * 60 * 60 * 1000,
        isPublic: true,
        category: "career",
        imageUrl: undefined,
        createdBy: userIds[1]!,
      },
      {
        title: "Alumni Homecoming Weekend",
        description:
          "Celebrate with your classmates during our annual homecoming festivities.",
        startDate: now + 30 * 24 * 60 * 60 * 1000,
        endDate: now + 32 * 24 * 60 * 60 * 1000,
        location: "University Campus",
        isVirtual: false,
        virtualLink: undefined,
        maxAttendees: 500,
        registrationDeadline: now + 25 * 24 * 60 * 60 * 1000,
        isPublic: true,
        category: "social",
        imageUrl: undefined,
        createdBy: userIds[0]!,
      },
    ];

    const eventIds = await Promise.all(
      testEvents.map((evt) => ctx.db.insert("events", evt)),
    );

    // Optional: a couple of registrations
    await ctx.db.insert("eventRegistrations", {
      eventId: eventIds[0]!,
      userId: userIds[2]!,
      registeredAt: now,
      status: "registered",
    });
    await ctx.db.insert("eventRegistrations", {
      eventId: eventIds[1]!,
      userId: userIds[3]!,
      registeredAt: now,
      status: "registered",
    });

    return { success: true, message: "Seeded users, alumni, events, and registrations." };
  },
});